### ISSUE TITLE
Typo Initical in Feedback Agreement

### ISSUE THREAD

**Issue by BirgitBoss** [OpenManufacturingPlatform/Contribute-to-OMP-Public-Repos#1]
There is a typo in the last sentence of the feedback agreement: Initical ==> Initial

**Comment by jpradocueva** [comment]
Thanks it has been resolved by  https://github.com/OpenManufacturingPlatform/Contribute-to-OMP-Public-Repos/commit/a1b48c8a64e3acfc5b51926b295cd610e7abf67d
